spring:
  application:
    name: adoption
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/revature
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
# PostgreSQL DB
  datasource:
    url: jdbc:postgresql://localhost:5432/pets
    username: admin
    password: password
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # create-drop means the database is fresh on each restart
    hibernate:
      ddl-auto: create-drop

jwt:
  auth:
    converter:
      resource-id: pet-app
      principal-attribute: preferred_username


cors:
  allowed:
    origins: http://localhost:5173
    methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
    headers: "*"
  allow:
    credentials: true

